<?php
# Generated by protoc-gen-twirp_php, DO NOT EDIT.
# source: haberdasher.proto

namespace Twirp\Example\Haberdasher;

use Google\Protobuf\Internal\Message;

class HaberdasherStub implements HaberdasherInterface
{

    public $onMakeHat;

    public function makeHat(Size $size): Hat
    {
        if ($this->$onMakeHat) {
            return $this->$onMakeHat($size);
        }
        throw new \BadMethodCallException("Method not stubbed");
    }

}
