<?php
# Generated by protoc-gen-twirp_php, DO NOT EDIT.
# source: haberdasher.proto

namespace AppBundle\Twirp;

class HaberdasherNoop implements HaberdasherInterface
{

    public function makeHat(Size $size): Hat
    {
        return new Hat();
    }

}
