<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: haberdasher.proto

namespace GPBMetadata;

class Haberdasher
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0afe010a1168616265726461736865722e70726f746f121974776972702e" .
            "6578616d706c652e686162657264617368657222160a0453697a65120e0a" .
            "06696e6368657318012001280522320a03486174120e0a06696e63686573" .
            "180120012805120d0a05636f6c6f72180220012809120c0a046e616d6518" .
            "032001280932590a0b4861626572646173686572124a0a074d616b654861" .
            "74121f2e74776972702e6578616d706c652e68616265726461736865722e" .
            "53697a651a1e2e74776972702e6578616d706c652e686162657264617368" .
            "65722e486174421f5a0b6861626572646173686572ca020f41707042756e" .
            "646c655c5477697270620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

