<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: clientcompat.proto

namespace Twirp\Clientcompat;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>twirp.clientcompat.ClientCompatMessage</code>
 */
class ClientCompatMessage extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string service_address = 1;</code>
     */
    private $service_address = '';
    /**
     * Generated from protobuf field <code>.twirp.clientcompat.ClientCompatMessage.CompatServiceMethod method = 2;</code>
     */
    private $method = 0;
    /**
     * Generated from protobuf field <code>bytes request = 3;</code>
     */
    private $request = '';

    public function __construct() {
        \GPBMetadata\Clientcompat::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>string service_address = 1;</code>
     * @return string
     */
    public function getServiceAddress()
    {
        return $this->service_address;
    }

    /**
     * Generated from protobuf field <code>string service_address = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setServiceAddress($var)
    {
        GPBUtil::checkString($var, True);
        $this->service_address = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.twirp.clientcompat.ClientCompatMessage.CompatServiceMethod method = 2;</code>
     * @return int
     */
    public function getMethod()
    {
        return $this->method;
    }

    /**
     * Generated from protobuf field <code>.twirp.clientcompat.ClientCompatMessage.CompatServiceMethod method = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setMethod($var)
    {
        GPBUtil::checkEnum($var, \Twirp\Clientcompat\ClientCompatMessage_CompatServiceMethod::class);
        $this->method = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes request = 3;</code>
     * @return string
     */
    public function getRequest()
    {
        return $this->request;
    }

    /**
     * Generated from protobuf field <code>bytes request = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setRequest($var)
    {
        GPBUtil::checkString($var, False);
        $this->request = $var;

        return $this;
    }

}

