<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: clientcompat.proto

namespace Twirp\Clientcompat;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>twirp.clientcompat.Empty</code>
 */
class PBEmpty extends \Google\Protobuf\Internal\Message
{

    public function __construct() {
        \GPBMetadata\Clientcompat::initOnce();
        parent::__construct();
    }

}

