<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: clientcompat.proto

namespace Twirp\Clientcompat;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>twirp.clientcompat.Req</code>
 */
class Req extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string v = 1;</code>
     */
    private $v = '';

    public function __construct() {
        \GPBMetadata\Clientcompat::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>string v = 1;</code>
     * @return string
     */
    public function getV()
    {
        return $this->v;
    }

    /**
     * Generated from protobuf field <code>string v = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setV($var)
    {
        GPBUtil::checkString($var, True);
        $this->v = $var;

        return $this;
    }

}

