<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: clientcompat.proto

namespace Twirp\Clientcompat;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>twirp.clientcompat.Resp</code>
 */
class Resp extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int32 v = 1;</code>
     */
    private $v = 0;

    public function __construct() {
        \GPBMetadata\Clientcompat::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>int32 v = 1;</code>
     * @return int
     */
    public function getV()
    {
        return $this->v;
    }

    /**
     * Generated from protobuf field <code>int32 v = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setV($var)
    {
        GPBUtil::checkInt32($var);
        $this->v = $var;

        return $this;
    }

}

