<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: clientcompat.proto

namespace Twirp\Clientcompat;

/**
 * Protobuf enum <code>Twirp\Clientcompat\ClientCompatMessage\CompatServiceMethod</code>
 */
class ClientCompatMessage_CompatServiceMethod
{
    /**
     * Generated from protobuf enum <code>NOOP = 0;</code>
     */
    const NOOP = 0;
    /**
     * Generated from protobuf enum <code>METHOD = 1;</code>
     */
    const METHOD = 1;
}

