<?php
# Generated by protoc-gen-twirp_php , DO NOT EDIT.
# clientcompat.proto

namespace Twirp\Clientcompat;

use Psr\Http\Message\ResponseInterface;

class CompatServiceException extends \Exception
{
    private $twirpCode;
    private $meta;

    public function __construct(ResponseInterface $response)
    {
        $data = @json_decode($response->getBody()->getContents(), true);

        if (isset($data['msg'])) {
            $msg = $data['msg'];
        } else {
            $msg = $response->getStatusCode() . ': Unknown server response: ' . $response->getBody()->getContents();
        }

        $this->twirpCode = isset($data['code']) ? $data['code'] : 'internal';
        $this->meta = isset($data['meta']) ? $data['meta']: [];
        parent::__construct($msg, $response->getStatusCode());
    }

    public function getTwirpCode(): string
    {
        return $this->twirpCode;
    }

    public function getMeta(): array
    {
        return $this->meta;
    }
}
